server:
  port: 8008

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/my_novel?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      max-lifetime: 1800000
      connection-timeout: 30000
      maximum-pool-size: 100
      connection-test-query: SELECT 1
  jpa:
    show-sql: false
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5Dialect
myconfig:
  host: http://www.jjxsw.com