spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

#    本地数据库
    url: jdbc:mysql://localhost/authentication?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - com.wangyb.learningdemo.authentication.config.BaseMapper
  identity: MYSQL
  not-empty: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    com.wangyb.learningdemo.authentication.mapper: trace

server:
  port: 8086

config:
  history:
    number: 7
  httpclient:
    conn-max-total: 20
    max-per-route: 10
    conn-timeout: 2000
    conn-request-timeout: 500
    socket-timeout: 5000
    retry-time: 2


wangyb:
   #创建初始管理员及后台用户的默认密码
   default-password: 123