spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/delivery_center?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
      web-stat-filter:
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10240Mb

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
  - com.potoyang.learn.securityjwt.mapper.BaseMapper
  identity: MYSQL
  not-empty: false

server:
  port: 8002
